#!/usr/bin/bash

HIDE(){ echo -en "\033[?25l";}
NORM(){ echo -en "\033[?12l\033[?25h";}

HIDE; printf "[+] Checking for Update...      \r\e[0m"
changed=0
git remote update &> /dev/null && git status -uno | grep -q 'Your branch is behind' && changed=1
if [ $changed = 1 ]; then

printf "[!] Termux-security Update Available  \r\e[0m"
sleep 1
printf "[!] Termux-security Updating...       \r\e[0m"
git stash &> /dev/null
git pull &> /dev/null
printf "[√] Termux-security Updated Successful." ;NORM
else
printf "[!] Theme-Engine Already Updated.                   \r\e[0;1m┃\e[0m"
NORM ;fi

